### PR TITLE
Added git documentation

### PR DESCRIPTION
**Pull request by badi**
**In progress** I'll merge this when done.

This change describes how to use Git for the Cloud Computing Courses.

ping @lee212 for review

### CODE REVIEW

**Comment by badi** [comment]
@laszewsk @lee212 I am close to merging this change if you would like to take a look and provide feedback.

**Comment by lee212** [comment]
Looks good to me except a few links missing in the rst. The missing links that I found are:

* `FutureSystems documentation`_ : http://cloudmesh.github.io/introduction_to_cloud_computing/accounts/accounts.html
* `how to upload an SSH Key`_ : http://cloudmesh.github.io/introduction_to_cloud_computing/accounts/ssh.html#s-using-ssh

We have FutureGrid manuals here:http://futuregrid.github.io/manual/index.html and some pages are still useful for FutureSystems. However, I don't think we are going to use this manual.

**Comment by lee212** [comment]
One suggestion that I have is about **IMPORTANT** paragraphs. We have used some directives in sphinx documents for example, .. note::, .. tip::, or .. warning:: to distinguish paragraphs. IMPORTANT sentences could be into one of these directives?

**Comment by laszewsk** [comment]
we are not using anything from futuregrid.org <http://futuregrid.org/>. i have made lots of chnges and pulled most important content. there should not be a backwards link to futuregrid anywhere in our documentation …

if you find one let us know so we identify what to do.

**Pull request merged**
